# Generated by Django 5.0.6 on 2026-07-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='domain',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
